### ISSUE TITLE
CMakeLists.txt dans le src dus workspace

### ISSUE THREAD

**Issue by simchanu29** [EnstaBretagneClubRobo/Cordeliere_ROSws#11]
Je déconseille le fait de stocker le fichier `src/CMakelists.txt`. C'est un symlink vers le `CMakelist.txt` racine de ROS. C'est donc un fichier dépendant du système d'accueil du workspace et peut en perturber plus d'un.

Je conseille de le supprimer du repository distant et de l'ajouter dans le .gitignore (`src/CMakeLists.txt`) afin que les repositories locaux puissent fonctionner. Par contre, juste après le clonage du repository, il va donc falloir faire un catkin_init_workspace avant de compiler. Habituellement j'ajoute un script `install.sh` à la racine qui initialise le workspace, compile, source et modifie les droits du workspace`.

C'était juste un conseil en passant.

**Comment by TilletJ** [comment]
Thanks @simchanu29 !
